### ISSUE TITLE
Issue downloading DESED datset

### ISSUE THREAD

**Issue by niclas-b** [fgnt/pb_sed#10]
Hello,
using `python -m pb_sed.database.desed.download -db /path/to/desed` step in the readme instructions, I get following error:
`ImportError: cannot import name 'FastChildWatcher' from 'asyncio' (C:\Users\username\AppData\Local\Programs\Python\Python39\lib\asyncio\__init__.py)`
All previous steps worked fine. Do you have an idea what could be the reason for it?

Edit: Seeing that the FastChildWatcher class is contained in unix_events.py, is it fact that the pb_sed repository is made for use only on Linux, not on Windows?

Best Regards

**Comment by JanekEbb** [comment]
Hi Niclas. yes, the repo is made for unix based OS. Sorry for the inconvenience.

**Comment by niclas-b** [comment]
Thanks for the answer.
The issue is solved according to
https://github.com/turpaultn/DESED/issues/60
by commenting out `from asyncio import FastChildWatcher` in desed/download.py

Edit: I don't think the complete command will work on Windows anyways, though. I'm using Linux now.
