### ISSUE TITLE
Assert error: The datasets are not indexable

### ISSUE THREAD

**Issue by ZHAO-Fengnian** [fgnt/pb_sed#2]
A bug in pb_sed/experiments/dcase_2020_task4/data.py
In 60th line,
    training_set = lazy_dataset.intersperse(
        *[
            ds.shuffle(reshuffle=True).tile(repetitions[name]) #zfn: the reshuffle disables the indexable, causing an error
            for name, ds in datasets.items()
        ]
    )
The reshuffle should not be True otherwise it will change the indexable of the datasets to False, causing an assert error in intersperse: the location is in lazy_dataset/core.py, line2138:
assert all([dataset.indexable for dataset in self.input_datasets])

**Comment by JanekEbb** [comment]
I missed to merge a pull request in lazy_dataset which allows intersperse with non-indexable datasets. Fixed now. Thanks!
