### ISSUE TITLE
Issue downloading data

### ISSUE THREAD

**Issue by qkrguswn2401** [fgnt/pb_sed#4]
![image](https://user-images.githubusercontent.com/36841216/118984741-c11daa80-b9b8-11eb-84dc-7b67e5259bbe.png)

I have trouble downloading dataset.  
How do I solve this issue?

**Comment by JanekEbb** [comment]
Hi, seems like some of the urls have been removed. I will look into it shortly. Thanks!

**Comment by arshinmar** [comment]
Hello,

https://github.com/fgnt/pb_sed/blob/0ce516e4c49c77656ff6aee200f45040b7d0eb83/pb_sed/database/desed/download.py#L69

I believe the error arises from how the path in the above code snippet does not exist in the main DESED repo.

I believe the correct path is now actually 

https://raw.githubusercontent.com/turpaultn/DESED/master/data/real/metadata.

When I changed the value of the remote variable to this line, the above error stopped occurring.

Hope this helps!

**Comment by qkrguswn2401** [comment]
Thank you taking care of the issue.  I have now encountered another issue, 
![image](https://user-images.githubusercontent.com/36841216/119138144-8b41fa00-ba7c-11eb-83c1-403b10c1b5ad.png)
