### ISSUE TITLE
Reproductionablity for createjson

### ISSUE THREAD

**Issue by qkrguswn2401** [fgnt/pb_sed#5]
![image](https://user-images.githubusercontent.com/36841216/119225266-ba6c7000-bb3d-11eb-9b7c-d9d3ea013780.png)
 
should the number of labels be 10?

**Comment by qkrguswn2401** [comment]
![image](https://user-images.githubusercontent.com/36841216/119225656-f6083980-bb3f-11eb-9a1c-2c8179db4446.png)
is this the expected result?

**Comment by nathanielatom** [comment]
Sounds like according to @arshinmar that it is supposed to be 10. See the `DESED dataset` section in http://dcase.community/challenge2020/task-sound-event-detection-and-separation-in-domestic-environments

**Comment by JanekEbb** [comment]
Yes @nathanielatom is right, it is supposed to be 10. In your first screenshot it looks like you had some other tsv files (those with the durations suffix) within the metadata directory which may have lead to the 19 event labels.
